### ISSUE TITLE
Circuit problem

### ISSUE THREAD

**Issue by lky7956** [mr-kenhoff/STM#1]
Hello
I want to ask some questions about the circuit.
Some parts on the circuit diagram are "OPT". How much does it represent? (For example, R1.R3.C3 of Head-Interconnect, etc.)

thanks

**Comment by jherkenhoff** [comment]
Hey!

The parts marked with "OPT" are optional. The footprints are printed on the PCB but I did not populate them.
Exception: R3 on Head interconnect should be a 0 Ohm Resistor (or a simple solder bridge). Sorry that I did not mark this one properly.

Cheers

**Comment by jherkenhoff** [comment]
I updated the value for R3 in the schematic. Please let me know if there are more ambiguities in the schematic.

**Comment by lky7956** [comment]
Thanks for your reply.

I see these problems
C5 & C6 of Tunnelling-Amp (ELN RV2-35V220MU is 22uF,but circuit diagram shows 220uF)
https://www.reichelt.de/de/de/smd-elko-22-f-35v-2000h-eln-rv2-35v220mu-p246738.html?r=1

L1 of Supply-Board(Inductor_SMD:L_Fastron_PISN_Handsoldering,I didn’t see 3.3uF in PISN on fastron official website, only 33uF)
https://fastrongroup.com/smd-power-inductors/pisn

U3 of Supply-Board(The value should be LM317, but the value indicates 240R)

**Comment by lky7956** [comment]
Thanks for your reply.

I see these problems
C5 & C6 of Tunnelling-Amp (ELN RV2-35V220MU is 22uF,but circuit diagram shows 220uF)
https://www.reichelt.de/de/de/smd-elko-22-f-35v-2000h-eln-rv2-35v220mu-p246738.html?r=1

L1 of Supply-Board(Inductor_SMD:L_Fastron_PISN_Handsoldering,I didn’t see 3.3uF in PISN on fastron official website, only 33uF)
https://fastrongroup.com/smd-power-inductors/pisn

U3 of Supply-Board(The value should be LM317, but the value indicates 240R)

**Comment by jherkenhoff** [comment]
Thanks a lot for your Help! I fixed the mentioned issues in the schematic :)
